baseURL = "https://tygerbytes.github.io/wp2hugoref/"
languageCode = "en-us"
publishDir = "docs"

title = "Migrating WordPress to Hugo: Course Reference"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "Helpful Links"
sidebarColor = "default"
customCss = []

[[menu.shortcuts]]
name = "wp2hugo-ref on GitHub"
url = "https://github.com/tygerbytes/wp2hugo-ref"
weight = 10

[[menu.shortcuts]]
name = "Hugo docs"
url = "https://gohugo.io/documentation/"
weight = 20

[[menu.shortcuts]]
name = "@tygertec"
url = "https://twitter.com/tygertec"
weight = 10

[[menu.shortcuts]]
name = "tygertec.com"
url = "https://www.tygertec.com"
weight = 10

[[menu.shortcuts]]
name = "The Udemy Course: WP2Hugo"
url = "https://www.udemy.com/wp-to-hugo/?couponCode=COURSEREFS19"
weight = 10
